#!/usr/bin/env bash
#
# sync.sh — propagate the .shared/ source of truth into each AI tool's directory.
# (Also aliased as "skillshare" / "vsync" in some setups.)
#
#   .shared/skills/*   ──┬─▶ .claude/skills/      (verbatim + DO-NOT-EDIT banner)
#                        ├─▶ .cursor/skills/
#                        ├─▶ .codex/skills/
#                        └─▶ .cursor/rules/<name>.mdc   (generated rule per skill)
#
#   .shared/prompts/*  ──┬─▶ .claude/commands/<name>.md  (as slash commands)
#                        ├─▶ .cursor/commands/<name>.md
#                        └─▶ .codex/prompts/<name>.md
#
# Generated files are tracked in .sync-manifest so removed sources are cleaned up.
#
# Usage:
#   ./scripts/sync.sh            propagate (default)
#   ./scripts/sync.sh --check    exit non-zero if any tool is out of date (for CI)
#   ./scripts/sync.sh --help
#
set -euo pipefail

# ---- locate repo root (the directory that contains .shared) ------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

SHARED="$ROOT/.shared"
MANIFEST="$ROOT/.sync-manifest"

if [[ ! -d "$SHARED" ]]; then
  echo "error: no .shared/ directory found at $SHARED" >&2
  exit 2
fi

# ---- mode --------------------------------------------------------------------
MODE="sync"
case "${1:-}" in
  --check) MODE="check" ;;
  --help|-h)
    sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
    exit 0 ;;
  "" ) ;;
  * ) echo "unknown argument: $1 (try --help)" >&2; exit 2 ;;
esac

# ---- pretty output -----------------------------------------------------------
if [[ -t 1 ]]; then BOLD=$'\033[1m'; DIM=$'\033[2m'; GRN=$'\033[32m'; YEL=$'\033[33m'; RED=$'\033[31m'; RST=$'\033[0m'
else BOLD=""; DIM=""; GRN=""; YEL=""; RED=""; RST=""; fi

CHANGED=0      # files written/updated (sync mode)
DRIFT=0        # files out of date (check mode)
EMITTED=0      # total generated files this run
TMP="$(mktemp)"; trap 'rm -f "$TMP"' EXIT

NEW_MANIFEST=""   # newline-separated list of paths generated this run

rel() { printf '%s' "${1#$ROOT/}"; }

# emit <dst-abs> <src-tmp-with-content>
# sync mode: write if different; check mode: record drift if different.
emit() {
  local dst="$1" src="$2" r; r="$(rel "$dst")"
  NEW_MANIFEST+="$r"$'\n'
  EMITTED=$((EMITTED+1))
  if [[ -f "$dst" ]] && cmp -s "$src" "$dst"; then
    return 0
  fi
  if [[ "$MODE" == "check" ]]; then
    DRIFT=$((DRIFT+1))
    echo "  ${RED}drift${RST}  $r"
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    CHANGED=$((CHANGED+1))
    echo "  ${GRN}wrote${RST}  $r"
  fi
}

# read a frontmatter scalar: fm_field <file> <key>
fm_field() {
  awk -v key="$2" '
    /^---[[:space:]]*$/ { c++; next }
    c==1 && $0 ~ "^"key":" { sub("^"key":[[:space:]]*",""); print; exit }
  ' "$1"
}

# body after frontmatter (or whole file if none): strip_fm <file>
strip_fm() {
  if [[ "$(head -n1 "$1")" == "---" ]]; then
    awk 'BEGIN{c=0} /^---[[:space:]]*$/{c++; next} c>=2{print}' "$1"
  else
    cat "$1"
  fi
}

banner() { # banner <source-rel> <comment-style:html|hash>
  local src="$1"
  echo "<!-- GENERATED by scripts/sync.sh from ${src} — DO NOT EDIT. Run ./scripts/sync.sh -->"
}

# ---- 1. skills → three tools (verbatim + banner) -----------------------------
echo "${BOLD}skills${RST} ${DIM}(.shared/skills → .claude .cursor .codex)${RST}"
SKILL_TARGETS=(".claude/skills" ".cursor/skills" ".codex/skills")

if [[ -d "$SHARED/skills" ]]; then
  for skilldir in "$SHARED"/skills/*/; do
    [[ -d "$skilldir" ]] || continue
    name="$(basename "$skilldir")"
    for file in "$skilldir"*; do
      [[ -f "$file" ]] || continue
      base="$(basename "$file")"
      srcrel="$(rel "$file")"
      # Build the synced content into $TMP
      if [[ "$base" == "SKILL.md" && "$(head -n1 "$file")" == "---" ]]; then
        # insert banner immediately after the frontmatter block
        awk -v b="$(banner "$srcrel")" '
          /^---[[:space:]]*$/ { print; c++; if (c==2) print b; next }
          { print }
        ' "$file" > "$TMP"
      else
        cp "$file" "$TMP"
      fi
      for t in "${SKILL_TARGETS[@]}"; do
        emit "$ROOT/$t/$name/$base" "$TMP"
      done
    done

    # generated Cursor rule for this skill
    desc="$(fm_field "$skilldir/SKILL.md" description)"
    {
      echo "---"
      echo "description: ${desc}"
      echo "globs:"
      echo "alwaysApply: false"
      echo "---"
      banner "$(rel "$skilldir/SKILL.md")"
      echo
      echo "# ${name} (rule)"
      echo
      echo "Auto-generated from the \`${name}\` skill. Full guidance:"
      echo "\`.cursor/skills/${name}/SKILL.md\`."
      echo
      strip_fm "$skilldir/SKILL.md"
    } > "$TMP"
    emit "$ROOT/.cursor/rules/${name}.mdc" "$TMP"
  done
fi

# ---- 2. prompts → commands / codex prompts -----------------------------------
echo "${BOLD}prompts${RST} ${DIM}(.shared/prompts → .claude/commands .cursor/commands .codex/prompts)${RST}"
if [[ -d "$SHARED/prompts" ]]; then
  for file in "$SHARED"/prompts/*.md; do
    [[ -f "$file" ]] || continue
    name="$(basename "$file" .md)"
    desc="$(fm_field "$file" description)"
    srcrel="$(rel "$file")"
    body="$(strip_fm "$file")"

    # Claude + Cursor slash command (frontmatter description + banner + body)
    for cmddir in ".claude/commands" ".cursor/commands"; do
      {
        echo "---"
        echo "description: ${desc}"
        echo "---"
        banner "$srcrel"
        echo
        printf '%s\n' "$body"
      } > "$TMP"
      emit "$ROOT/$cmddir/${name}.md" "$TMP"
    done

    # Codex prompt (banner + full original)
    {
      banner "$srcrel"
      echo
      cat "$file"
    } > "$TMP"
    emit "$ROOT/.codex/prompts/${name}.md" "$TMP"
  done
fi

# ---- 3. per-tool skills README banner ----------------------------------------
for t in "${SKILL_TARGETS[@]}"; do
  {
    echo "# Generated directory — do not edit"
    echo
    echo "Synced from \`.shared/skills/\` by \`scripts/sync.sh\`."
    echo "Edit the originals in \`.shared/skills/\` and re-run the sync."
  } > "$TMP"
  emit "$ROOT/$t/README.md" "$TMP"
done

# ---- 4. stale cleanup via manifest -------------------------------------------
STALE=0
if [[ -f "$MANIFEST" ]]; then
  while IFS= read -r old; do
    [[ -n "$old" ]] || continue
    if ! grep -qxF "$old" <<< "$NEW_MANIFEST"; then
      STALE=$((STALE+1))
      if [[ "$MODE" == "check" ]]; then
        DRIFT=$((DRIFT+1))
        echo "  ${RED}stale${RST}  $old"
      else
        rm -f "$ROOT/$old"
        echo "  ${YEL}prune${RST}  $old"
      fi
    fi
  done < "$MANIFEST"
fi

# ---- 5. summary --------------------------------------------------------------
echo
if [[ "$MODE" == "check" ]]; then
  if [[ "$DRIFT" -gt 0 ]]; then
    echo "${RED}✗ out of date${RST}: $DRIFT file(s) differ. Run ./scripts/sync.sh" >&2
    exit 1
  fi
  echo "${GRN}✓ in sync${RST}: $EMITTED generated file(s) all current."
else
  printf '%s\n' "$NEW_MANIFEST" | grep -v '^$' | sort > "$MANIFEST"
  echo "${GRN}✓ synced${RST}: $EMITTED file(s) generated, $CHANGED written/updated, $STALE pruned."
fi
